accounts:
  - name: alex
    coins: ["444token", "444stake"]
  - name: athena
    coins: ["10000token", "100000000stake"]
  - name: bob
    oins: ["10000token", "100000000stake"]
  - name: jen
    coins: ["10000token", "100000000stake"]
validator:
  name: athena
  staked: "100000000stake"
client:
  openapi:
    path: "docs/static/openapi.yml"
faucet:
  name: bob
  coins: ["5token", "100000stake"]
build:
  main: "cmd/terpd"
